### ISSUE TITLE
Issue with enableGeocoding: false

### ISSUE THREAD

**Issue by trinityblu3** [dpa99c/phonegap-launch-navigator-example#12]
I'm using this plugin to pass the address/lat-long to the users navigational device. I have another system that runs that already gets the lat-long, so I don't need the geocoding to be enabled (and paying for the API with my company is a huge issue - a lot of red tape involved and we don't need it to geocode anyway). 

After reading the documentation, and the readme.md, I saw that this could be disabled with the options. I was able to pass that and the lat/long information to the device when doing a Phonegap build, but now that I'm doing a test build, it's really throwing an error, saying I need a ',' somewhere. 

Here is the code I'm using: 
`let options: LaunchNavigatorOptions = {
                  enableGeocoding: false
                };
                this.launchnavigator.navigate(splitvals[1], [lat, long], options);`

Any idea what am I doing wrong? I can't find any examples on  how it should be.

**Comment by dpa99c** [comment]
If you always pass a lat/lon coordinate to the plugin, then you don't need to disable the plugin's geocoding capability because it will never be used, since (at least currently) all supported navigation apps directly support passing of lat/lon coordinates as you can see on the [App location type support Wiki page](https://github.com/dpa99c/phonegap-launch-navigator/wiki/App-location-type-support).

However if you want to disable geocoding, you can see this working correctly in the [AdvancedExample app](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/AdvancedExample) within this repo.
If you build and run this, you'll see there's a [checkbox](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.html#L114) which when unchecked [disables geocoding in the plugin](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/AdvancedExample/www/index.js#L142).

Once geocoding is disabled, if you select an address as the destination/start location for an app which doesn't support address as an input, the plugin will return an error:

<img width="300" src="https://user-images.githubusercontent.com/2345062/53366372-51382b00-393b-11e9-96f5-36a294befd15.png"/>

As you'll see from this, disabling of geocoding works perfectly well in this plugin.

I don't know the cause of your error related to a missing comma, maybe that's arising in the [Ionic Native Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/launch-navigator/index.ts), however that's not part of this plugin and is owned/maintained by Ionic.
