### ISSUE TITLE
Ionic 3 + Angular 4 + LaunchNavigator Plugin

### ISSUE THREAD

**Issue by Kale-gz** [dpa99c/phonegap-launch-navigator-example#8]
I've experienced a problem using this plugin within the following environment:
`global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 5.1.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.4`

I've installed the plugin using the following commands:
`ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator

npm install --save @ionic-native/launch-navigator`

In the code I've updated the file /src/app/app.module.ts adding the following lines:
`import { LaunchNavigator } from '@ionic-native/launch-navigator'; `
to import the service into the module nG
`  providers: [
   ...
    LaunchNavigator,`

After this, into my code I invoke the plugin in this way:
`import { LaunchNavigator, LaunchNavigatorOptions } from '@ionic-native/launch-navigator';

export class InformazioniPage{

 constructor(private launchNavigator: LaunchNavigator) {}

navigate(): void{
      this.launchNavigator.navigate('Toronto', {start: 'Rome'})
        .then(
          success => console.log('Launched navigator'),
          error => console.log('Error launching navigator', error)
        );
  }`

Then in my html I call the function inserting 
`(click)="navigate()"`

This works on a device with Android 7 but the code stuck on a device with Android 5, there is any way to fix this?
After the button pression the app simply doesn't respond anymore, no choice panel appears.

**Comment by dpa99c** [comment]
Firstly, there's currently a disparity with the Ionic Native wrapper for this plugin, because a major new version (v4) of the plugin was just released. There is [an issue](https://github.com/ionic-team/ionic-native/issues/1738) open against Ionic Native to update it to reflect the v4 API, but in the meantime if you are using this plugin with Ionic Native, I would recommend sticking with v3:

    ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator@3

> This works on a device with Android 7 but the code stuck on a device with Android 5, there is any way to fix this?
After the button pression the app simply doesn't respond anymore, no choice panel appears.

If you still encounter this error after doing the above and the `Ionic2Example` from the example project still doesn't work with Ionic 3, please let me know. I will have a look at updating it to `Ionic3Example` when I get some time.

**Comment by Kale-gz** [comment]
Thank you for your reply and promptness!!
I've disinstalled the plugin and reinstalled it using the @3 notation. Now it works on Andorid 5.1.1 device too!

**Comment by dpa99c** [comment]
Added [Ionic3Example](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/Ionic3Example)

**Comment by maximdevFR** [comment]
Nice version for ionic 3 
ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator@3

**Comment by 1antares1** [comment]
This is the combination that works for me:
**"@ionic-native/launch-navigator": "^4.7.0",**
**"uk.co.workingedge.phonegap.plugin.launchnavigator": "^4.2.2",**
